##    -   Pairwise Differences


fiber<- read.csv("fiber.csv")
OneWayFit <- aov(IDF~race, data=fiber)
TukeyHSD(OneWayFit)
library(multcomp)
PairComps <- glht(OneWayFit, linfct=mcp(race="Tukey"))
summary(PairComps)
cld(PairComps)

fiber<- read.csv("fiber.csv")
OneWayFit <- aov(SDF~race, data=fiber)
TukeyHSD(OneWayFit)
library(multcomp)
PairComps <- glht(OneWayFit, linfct=mcp(race="Tukey"))
summary(PairComps)
cld(PairComps)

fiber<- read.csv("fiber.csv")
OneWayFit <- aov(Raff~race, data=fiber)
TukeyHSD(OneWayFit)
library(multcomp)
PairComps <- glht(OneWayFit, linfct=mcp(race="Tukey"))
summary(PairComps)
cld(PairComps)

fiber<- read.csv("fiber.csv")
OneWayFit <- aov(Stach~race, data=fiber)
TukeyHSD(OneWayFit)
library(multcomp)
PairComps <- glht(OneWayFit, linfct=mcp(race="Tukey"))
summary(PairComps)
cld(PairComps)

fiber<- read.csv("fiber.csv")
OneWayFit <- aov(Verb~race, data=fiber)
TukeyHSD(OneWayFit)
library(multcomp)
PairComps <- glht(OneWayFit, linfct=mcp(race="Tukey"))
summary(PairComps)
cld(PairComps)

fiber<- read.csv("fiber.csv")
OneWayFit <- aov(TOligos~race, data=fiber)
TukeyHSD(OneWayFit)
library(multcomp)
PairComps <- glht(OneWayFit, linfct=mcp(race="Tukey"))
summary(PairComps)
cld(PairComps)

fiber<- read.csv("fiber.csv")
OneWayFit <- aov(TDF~race, data=fiber)
TukeyHSD(OneWayFit)
library(multcomp)
PairComps <- glht(OneWayFit, linfct=mcp(race="Tukey"))
summary(PairComps)
cld(PairComps)