library(data.table)
fiber.one<- read.csv("fiber_facet.csv")

idf.black <- subset(fiber.one, ftype=="IDF" & mktclass=="black")
idf.blackmottle <- subset(fiber.one, ftype=="IDF" & mktclass=="blackmottle")
idf.carioca <- subset(fiber.one, ftype=="IDF" & mktclass=="carioca")
idf.flordemayo <- subset(fiber.one, ftype=="IDF" & mktclass=="flordemayo")
idf.GN <- subset(fiber.one, ftype=="IDF" & mktclass=="GN")
idf.navy <- subset(fiber.one, ftype=="IDF" & mktclass=="navy")
idf.pink <- subset(fiber.one, ftype=="IDF" & mktclass=="pink")
idf.pinto <- subset(fiber.one, ftype=="IDF" & mktclass=="pinto")
idf.redmottle <- subset(fiber.one, ftype=="IDF" & mktclass=="redmottle")
idf.smallred <- subset(fiber.one, ftype=="IDF" & mktclass=="smallred")
idf.smallwhite <- subset(fiber.one, ftype=="IDF" & mktclass=="smallwhite")
idf.tan <- subset(fiber.one, ftype=="IDF" & mktclass=="tan")

sdf.black <- subset(fiber.one, ftype=="SDF" & mktclass=="black")
sdf.blackmottle <- subset(fiber.one, ftype=="SDF" & mktclass=="blackmottle")
sdf.carioca <- subset(fiber.one, ftype=="SDF" & mktclass=="carioca")
sdf.flordemayo <- subset(fiber.one, ftype=="SDF" & mktclass=="flordemayo")
sdf.GN <- subset(fiber.one, ftype=="SDF" & mktclass=="GN")
sdf.navy <- subset(fiber.one, ftype=="SDF" & mktclass=="navy")
sdf.pink <- subset(fiber.one, ftype=="SDF" & mktclass=="pink")
sdf.pinto <- subset(fiber.one, ftype=="SDF" & mktclass=="pinto")
sdf.redmottle <- subset(fiber.one, ftype=="SDF" & mktclass=="redmottle")
sdf.smallred <- subset(fiber.one, ftype=="SDF" & mktclass=="smallred")
sdf.smallwhite <- subset(fiber.one, ftype=="SDF" & mktclass=="smallwhite")
sdf.tan <- subset(fiber.one, ftype=="SDF" & mktclass=="tan")

verb.black <- subset(fiber.one, ftype=="Verb" & mktclass=="black")
verb.blackmottle <- subset(fiber.one, ftype=="Verb" & mktclass=="blackmottle")
verb.carioca <- subset(fiber.one, ftype=="Verb" & mktclass=="carioca")
verb.flordemayo <- subset(fiber.one, ftype=="Verb" & mktclass=="flordemayo")
verb.GN <- subset(fiber.one, ftype=="Verb" & mktclass=="GN")
verb.navy <- subset(fiber.one, ftype=="Verb" & mktclass=="navy")
verb.pink <- subset(fiber.one, ftype=="Verb" & mktclass=="pink")
verb.pinto <- subset(fiber.one, ftype=="Verb" & mktclass=="pinto")
verb.redmottle <- subset(fiber.one, ftype=="Verb" & mktclass=="redmottle")
verb.smallred <- subset(fiber.one, ftype=="Verb" & mktclass=="smallred")
verb.smallwhite <- subset(fiber.one, ftype=="Verb" & mktclass=="smallwhite")
verb.tan <- subset(fiber.one, ftype=="Verb" & mktclass=="tan")

raff.black <- subset(fiber.one, ftype=="Raff" & mktclass=="black")
raff.blackmottle <- subset(fiber.one, ftype=="Raff" & mktclass=="blackmottle")
raff.carioca <- subset(fiber.one, ftype=="Raff" & mktclass=="carioca")
raff.flordemayo <- subset(fiber.one, ftype=="Raff" & mktclass=="flordemayo")
raff.GN <- subset(fiber.one, ftype=="Raff" & mktclass=="GN")
raff.navy <- subset(fiber.one, ftype=="Raff" & mktclass=="navy")
raff.pink <- subset(fiber.one, ftype=="Raff" & mktclass=="pink")
raff.pinto <- subset(fiber.one, ftype=="Raff" & mktclass=="pinto")
raff.redmottle <- subset(fiber.one, ftype=="Raff" & mktclass=="redmottle")
raff.smallred <- subset(fiber.one, ftype=="Raff" & mktclass=="smallred")
raff.smallwhite <- subset(fiber.one, ftype=="Raff" & mktclass=="smallwhite")
raff.tan <- subset(fiber.one, ftype=="Raff" & mktclass=="tan")

stach.black <- subset(fiber.one, ftype=="Stach" & mktclass=="black")
stach.blackmottle <- subset(fiber.one, ftype=="Stach" & mktclass=="blackmottle")
stach.carioca <- subset(fiber.one, ftype=="Stach" & mktclass=="carioca")
stach.flordemayo <- subset(fiber.one, ftype=="Stach" & mktclass=="flordemayo")
stach.GN <- subset(fiber.one, ftype=="Stach" & mktclass=="GN")
stach.navy <- subset(fiber.one, ftype=="Stach" & mktclass=="navy")
stach.pink <- subset(fiber.one, ftype=="Stach" & mktclass=="pink")
stach.pinto <- subset(fiber.one, ftype=="Stach" & mktclass=="pinto")
stach.redmottle <- subset(fiber.one, ftype=="Stach" & mktclass=="redmottle")
stach.smallred <- subset(fiber.one, ftype=="Stach" & mktclass=="smallred")
stach.smallwhite <- subset(fiber.one, ftype=="Stach" & mktclass=="smallwhite")
stach.tan <- subset(fiber.one, ftype=="Stach" & mktclass=="tan")

toligos.black <- subset(fiber.one, ftype=="TOligos" & mktclass=="black")
toligos.blackmottle <- subset(fiber.one, ftype=="TOligos" & mktclass=="blackmottle")
toligos.carioca <- subset(fiber.one, ftype=="TOligos" & mktclass=="carioca")
toligos.flordemayo <- subset(fiber.one, ftype=="TOligos" & mktclass=="flordemayo")
toligos.GN <- subset(fiber.one, ftype=="TOligos" & mktclass=="GN")
toligos.navy <- subset(fiber.one, ftype=="TOligos" & mktclass=="navy")
toligos.pink <- subset(fiber.one, ftype=="TOligos" & mktclass=="pink")
toligos.pinto <- subset(fiber.one, ftype=="TOligos" & mktclass=="pinto")
toligos.redmottle <- subset(fiber.one, ftype=="TOligos" & mktclass=="redmottle")
toligos.smallred <- subset(fiber.one, ftype=="TOligos" & mktclass=="smallred")
toligos.smallwhite <- subset(fiber.one, ftype=="TOligos" & mktclass=="smallwhite")
toligos.tan <- subset(fiber.one, ftype=="TOligos" & mktclass=="tan")

tdf.black <- subset(fiber.one, ftype=="TDF" & mktclass=="black")
tdf.blackmottle <- subset(fiber.one, ftype=="TDF" & mktclass=="blackmottle")
tdf.carioca <- subset(fiber.one, ftype=="TDF" & mktclass=="carioca")
tdf.flordemayo <- subset(fiber.one, ftype=="TDF" & mktclass=="flordemayo")
tdf.GN <- subset(fiber.one, ftype=="TDF" & mktclass=="GN")
tdf.navy <- subset(fiber.one, ftype=="TDF" & mktclass=="navy")
tdf.pink <- subset(fiber.one, ftype=="TDF" & mktclass=="pink")
tdf.pinto <- subset(fiber.one, ftype=="TDF" & mktclass=="pinto")
tdf.redmottle <- subset(fiber.one, ftype=="TDF" & mktclass=="redmottle")
tdf.smallred <- subset(fiber.one, ftype=="TDF" & mktclass=="smallred")
tdf.smallwhite <- subset(fiber.one, ftype=="TDF" & mktclass=="smallwhite")
tdf.tan <- subset(fiber.one, ftype=="TDF" & mktclass=="tan")